/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_package;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import java.util.Random;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.Timer;
 

/**
 *
 * @author Jared Moodley
 */
public class Math_Quiz extends javax.swing.JFrame {
    
    /**
     * Creates new form Math_Quiz
     */
    int count = 30;
    Random random = new Random();
    int correct=0;
    int Num1;
    int Num2;
    int Tot;
    int Attempt= 1;
    int Question;
    int i = 0;
    String Operator;
    String Total;
    
    
    public Math_Quiz() {
        initComponents();
        btnExit.setVisible(false);
        btnAnswer.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        BtnGrCheckBox = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtTried = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorrect = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnAnswer = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtOperator = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        txtAnswer1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        checkAdd = new javax.swing.JCheckBox();
        checkSubtract = new javax.swing.JCheckBox();
        checkDivision = new javax.swing.JCheckBox();
        checkMultiply = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RDB1 = new javax.swing.JRadioButton();
        RDB2 = new javax.swing.JRadioButton();
        RDB3 = new javax.swing.JRadioButton();
        RDB4 = new javax.swing.JRadioButton();
        RDB5 = new javax.swing.JRadioButton();
        RDB6 = new javax.swing.JRadioButton();
        RDB7 = new javax.swing.JRadioButton();
        RDB8 = new javax.swing.JRadioButton();
        RDB9 = new javax.swing.JRadioButton();
        radioRandom = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rdOff = new javax.swing.JRadioButton();
        rdOn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtTried.setEditable(false);
        txtTried.setBackground(new java.awt.Color(204, 204, 255));
        txtTried.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTried.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTried.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tried:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Correct:");

        txtCorrect.setEditable(false);
        txtCorrect.setBackground(new java.awt.Color(204, 204, 255));
        txtCorrect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCorrect.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorrect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        btnExit.setBackground(new java.awt.Color(102, 0, 204));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAnswer.setBackground(new java.awt.Color(102, 0, 204));
        btnAnswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnswer.setForeground(new java.awt.Color(255, 255, 255));
        btnAnswer.setText("Check Answer");
        btnAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(102, 0, 204));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        txtNum1.setEditable(false);
        txtNum1.setBackground(new java.awt.Color(204, 204, 255));
        txtNum1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum1.setBorder(null);

        txtNum2.setEditable(false);
        txtNum2.setBackground(new java.awt.Color(204, 204, 255));
        txtNum2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum2.setBorder(null);

        txtOperator.setEditable(false);
        txtOperator.setBackground(new java.awt.Color(204, 204, 255));
        txtOperator.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtOperator.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOperator.setBorder(null);

        txtAnswer.setBackground(new java.awt.Color(204, 204, 255));
        txtAnswer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer.setText("??");
        txtAnswer.setBorder(null);

        txtAnswer1.setEditable(false);
        txtAnswer1.setBackground(new java.awt.Color(204, 204, 255));
        txtAnswer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAnswer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer1.setText("=");
        txtAnswer1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Type:");

        checkAdd.setBackground(new java.awt.Color(204, 204, 255));
        BtnGrCheckBox.add(checkAdd);
        checkAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkAdd.setText("Addition");
        checkAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAddActionPerformed(evt);
            }
        });

        checkSubtract.setBackground(new java.awt.Color(204, 204, 255));
        BtnGrCheckBox.add(checkSubtract);
        checkSubtract.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkSubtract.setText("Subtraction");
        checkSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSubtractActionPerformed(evt);
            }
        });

        checkDivision.setBackground(new java.awt.Color(204, 204, 255));
        BtnGrCheckBox.add(checkDivision);
        checkDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkDivision.setText("Division");
        checkDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDivisionActionPerformed(evt);
            }
        });

        checkMultiply.setBackground(new java.awt.Color(204, 204, 255));
        BtnGrCheckBox.add(checkMultiply);
        checkMultiply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkMultiply.setText("Multiplication");
        checkMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMultiplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMultiply)
                    .addComponent(checkDivision)
                    .addComponent(checkSubtract)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(checkAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(checkAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSubtract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDivision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkMultiply)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("No. of Questions");

        RDB1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB1);
        RDB1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB1.setText("1");

        RDB2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB2);
        RDB2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB2.setText("2");

        RDB3.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB3);
        RDB3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB3.setText("3");

        RDB4.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB4);
        RDB4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB4.setText("4");

        RDB5.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB5);
        RDB5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB5.setText("5");

        RDB6.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB6);
        RDB6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB6.setText("6");

        RDB7.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB7);
        RDB7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB7.setText("7");

        RDB8.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB8);
        RDB8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB8.setText("8");

        RDB9.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(RDB9);
        RDB9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RDB9.setText("9");

        radioRandom.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(radioRandom);
        radioRandom.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        radioRandom.setText("Random");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(39, 39, 39))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(RDB7)
                        .addGap(18, 18, 18)
                        .addComponent(RDB8)
                        .addGap(18, 18, 18)
                        .addComponent(RDB9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(RDB4)
                        .addGap(18, 18, 18)
                        .addComponent(RDB5)
                        .addGap(18, 18, 18)
                        .addComponent(RDB6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(RDB1)
                        .addGap(18, 18, 18)
                        .addComponent(RDB2)
                        .addGap(18, 18, 18)
                        .addComponent(RDB3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioRandom)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDB1)
                    .addComponent(RDB2)
                    .addComponent(RDB3))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDB6)
                    .addComponent(RDB5)
                    .addComponent(RDB4))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDB7)
                    .addComponent(RDB8)
                    .addComponent(RDB9)))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Timer");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        rdOff.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rdOff);
        rdOff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdOff.setText("Off");

        rdOn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rdOn);
        rdOn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdOn.setText("On");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdOff))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdOn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(rdOn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTried, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTried, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here: 
        
        txtTried.setText(Integer.toString(Attempt));
        Attempt= Attempt+1;
        btnAnswer.setVisible(true);
        btnStart.setVisible(false);
        btnExit.setVisible(false);
 // CountDown 30 Seconds**************************
 
if (rdOn.isSelected()){   
            count =30;
            jTextField1.setForeground(Color.black);
            Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 count--;
            if (count >= 0) {
              jTextField1.setText(Integer.toString(count));
              if(count == 15){
                  jTextField1.setForeground(Color.red);
              }
            } 
            
            if (count == 0 ){
              ((Timer) (e.getSource())).stop();
              JOptionPane.showMessageDialog(null, "Your Time's Up!!!");
              btnExit.setVisible(true);
              btnAnswer.setVisible(false);
              btnStart.setVisible(true);
            }
            
          }
        });
        timer.start();
        

}  

else{
Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 count--;
            
              if(count == 0) {
              ((Timer) (e.getSource())).stop();
              JOptionPane.showMessageDialog(null, "Your Time's Up!!!");
              btnExit.setVisible(true);
              btnAnswer.setVisible(false);
              btnStart.setVisible(true);
            }
              
              if (jTextField1.getText() == ""){
               ((Timer) (e.getSource())).stop();
                btnExit.setVisible(true);
                btnAnswer.setVisible(false);
                btnStart.setVisible(true);
            }
          }
        });
        timer.start();  

}
     
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswerActionPerformed
        // TODO add your handling code here:
        
        String Answer;
        int Num1 = random.nextInt(20)+ 1;
        int Num2 = random.nextInt(5) + 1;
        Total = Integer.toString(Tot);
        Answer = txtAnswer.getText();
        
        // Get Radio Button Value*********************************

        Enumeration<AbstractButton> bg = buttonGroup1.getElements();  
        while (bg.hasMoreElements()){
            JRadioButton jrdbtn = (JRadioButton) bg.nextElement();
            if(jrdbtn.isSelected()){
                String Val = jrdbtn.getText();
                if (Val == "Random"){
                    Question = random.nextInt(15)+1;
                    JOptionPane.showMessageDialog(null, Question);
                }
                else{ 
                Question = Integer.parseInt(Val);
                }   
                
                
                    if(Total.equals(Answer)){
                            JOptionPane.showMessageDialog(null, "Correct");
                            correct=correct+1;
                            txtCorrect.setText(Integer.toString(correct));
                            i= i+1;
                            if(i == Question){
                                
                                JOptionPane.showMessageDialog(null, "Congratulations!!!\n You've completed your quiz");                               
                                btnAnswer.setVisible(false);
                                btnStart.setVisible(true);
                                btnExit.setVisible(true);
                                
                                }
                            if(Operator == "+"){
                             Tot = Num1 + Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                            
                           if(Operator == "-"){
                             Tot = Num1 - Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                           if(Operator == "/"){
                             Tot = Num1 / Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                           if(Operator == "*"){
                             Tot = Num1 * Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }

                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Incorrect");
                            i= i+1;
                            if(i == Question){
                                JOptionPane.showMessageDialog(null, "Congratulations!!!\n You've completed your quiz");
                                btnAnswer.setVisible(false);
                                btnStart.setVisible(true);
                                btnExit.setVisible(true);
                                }
                        if(Operator == "+"){
                             Tot = Num1 + Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                        if(Operator == "-"){
                             Tot = Num1 - Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                           if(Operator == "/"){
                             Tot = Num1 / Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }
                           if(Operator == "*"){
                             Tot = Num1 * Num2;
                             txtAnswer.setText("");
                             txtNum1.setText(Integer.toString(Num1));
                             txtNum2.setText(Integer.toString(Num2));
                             
                            }                        
                    }                                                                                     
            }
        }
    }//GEN-LAST:event_btnAnswerActionPerformed

    private void checkAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAddActionPerformed
        // TODO add your handling code here:
        int Num1 = random.nextInt(20)+ 1;
        int Num2 = random.nextInt(5) + 1;
        
        
        if(checkAdd.isSelected()){
            Operator = "+";
            Tot = Num1 + Num2;
            txtNum1.setText(Integer.toString(Num1));
            txtOperator.setText(Operator);
            txtNum2.setText(Integer.toString(Num2));
            
        }
    }//GEN-LAST:event_checkAddActionPerformed

    private void checkSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSubtractActionPerformed
        // TODO add your handling code here:
        int Num1 = random.nextInt(20)+ 1;
        int Num2 = random.nextInt(5) + 1;
        
        
        if(checkSubtract.isSelected()){
            Operator = "-";
            Tot = Num1 - Num2;
            txtNum1.setText(Integer.toString(Num1));
            txtOperator.setText(Operator);
            txtNum2.setText(Integer.toString(Num2));
            
        }
    }//GEN-LAST:event_checkSubtractActionPerformed

    private void checkDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDivisionActionPerformed
        // TODO add your handling code here:
        int Num1 = random.nextInt(20)+ 1;
        int Num2 = random.nextInt(2) + 1;
        
        
        if(checkDivision.isSelected()){
            Operator = "/";
            Tot = Num1 / Num2;
            txtNum1.setText(Integer.toString(Num1));
            txtOperator.setText(Operator);
            txtNum2.setText(Integer.toString(Num2));
            
        }
    }//GEN-LAST:event_checkDivisionActionPerformed

    private void checkMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMultiplyActionPerformed
        // TODO add your handling code here:
        int Num1 = random.nextInt(20)+ 1;
        int Num2 = random.nextInt(5) + 1;
        
        
        if(checkMultiply.isSelected()){
            Operator = "*";
            Tot = Num1 * Num2;
            txtNum1.setText(Integer.toString(Num1));
            txtOperator.setText(Operator);
            txtNum2.setText(Integer.toString(Num2));
            
        }
    }//GEN-LAST:event_checkMultiplyActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math_Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Math_Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGrCheckBox;
    private javax.swing.JRadioButton RDB1;
    private javax.swing.JRadioButton RDB2;
    private javax.swing.JRadioButton RDB3;
    private javax.swing.JRadioButton RDB4;
    private javax.swing.JRadioButton RDB5;
    private javax.swing.JRadioButton RDB6;
    private javax.swing.JRadioButton RDB7;
    private javax.swing.JRadioButton RDB8;
    private javax.swing.JRadioButton RDB9;
    private javax.swing.JButton btnAnswer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkAdd;
    private javax.swing.JCheckBox checkDivision;
    private javax.swing.JCheckBox checkMultiply;
    private javax.swing.JCheckBox checkSubtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radioRandom;
    private javax.swing.JRadioButton rdOff;
    private javax.swing.JRadioButton rdOn;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtAnswer1;
    private javax.swing.JTextField txtCorrect;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtOperator;
    private javax.swing.JTextField txtTried;
    // End of variables declaration//GEN-END:variables
}
